# GitHub Actions CI Workflow Example
#
# This file is an example. To use it, copy it to a new file at
# .github/workflows/ci.yml in your project's repository.
#
# This workflow runs on every push and pull request to the 'main' branch.
# It installs dependencies, runs the linter, executes tests, and performs
# a security audit.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm run test:run

    - name: Run security audit
      run: npm audit --audit-level=high
